CREATE OR REPLACE FUNCTION CHECK_AGE_LIMIT (
    V_AGE_LIMIT IN NUMBER
) RETURN NUMBER IS
    V_AGE_LIMIT_ID NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        AGE_LIMITS.ID INTO V_AGE_LIMIT_ID
    FROM
        AGE_LIMITS
    WHERE
        AGE = V_AGE_LIMIT;
    RETURN V_AGE_LIMIT_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_AGE_LIMIT;