CREATE OR REPLACE FUNCTION CHECK_GENRE (
    V_GENRE IN VARCHAR2
) RETURN NUMBER IS
    V_GENRE_ID     NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        GENRES.ID INTO V_GENRE_ID
    FROM
        GENRES
    WHERE
        NAME = V_GENRE;
    RETURN V_GENRE_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO GENRES VALUES (
            GENRES_SEQ.NEXTVAL,
            V_GENRE
        ) RETURNING ID INTO V_GENRE_ID;
        RETURN V_GENRE_ID;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_GENRE;