CREATE OR REPLACE FUNCTION CHECK_AUTHOR (
    V_NAME IN VARCHAR2,
    V_SURNAME IN VARCHAR2
) RETURN NUMBER IS
    V_AUTHOR_ID    NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        AUTHORS.ID INTO V_AUTHOR_ID
    FROM
        AUTHORS
    WHERE
        NAME = V_NAME
        AND SURNAME = V_SURNAME;
    RETURN V_AUTHOR_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO AUTHORS VALUES (
            AUTHORS_SEQ.NEXTVAL,
            V_NAME,
            V_SURNAME
        ) RETURNING ID INTO V_AUTHOR_ID;
        RETURN V_AUTHOR_ID;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_AUTHOR;