CREATE OR REPLACE FUNCTION CHECK_BOOK (
    V_BOOK_NAME IN VARCHAR2,
    V_PUBLICATION_YEAR IN NUMBER,
    V_COST IN NUMBER,
    V_PUBLISHER_ID IN NUMBER,
    V_TYPE_ID IN NUMBER,
    V_AGE_LIMIT_ID IN NUMBER,
    V_DESCRIPTION IN VARCHAR2
) RETURN NUMBER IS
    V_BOOK_ID NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        stock.ID INTO V_BOOK_ID from stock
    WHERE
        book_name = V_BOOK_NAME
        and PUBLICATION_YEAR = V_PUBLICATION_YEAR 
        and COST = V_COST 
        and PUBLISHER_ID = V_PUBLISHER_ID 
        and DESCRIPTION = V_DESCRIPTION 
        and TYPE_ID = V_TYPE_ID 
        and AGE_LIMIT_ID = V_AGE_LIMIT_ID;
    RETURN V_BOOK_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_BOOK;