CREATE OR REPLACE FUNCTION CHECK_TAG (
    V_TAG IN VARCHAR2
) RETURN NUMBER IS
    V_TAG_ID       NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        TAGS.ID INTO V_TAG_ID
    FROM
        TAGS
    WHERE
        TAG_NAME = V_TAG;
    RETURN V_TAG_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO TAGS VALUES (
            TAGS_SEQ.NEXTVAL,
            V_TAG
        ) RETURNING ID INTO V_TAG_ID;
        RETURN V_TAG_ID;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_TAG;