CREATE OR REPLACE FUNCTION CHECK_PUBLISHER (
    V_PUBLISHER IN VARCHAR2
) RETURN NUMBER IS
    V_PUBLISHER_ID NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        PUBLISHERS.ID INTO V_PUBLISHER_ID
    FROM
        PUBLISHERS
    WHERE
        PUBLISHER_NAME = V_PUBLISHER;
    RETURN V_PUBLISHER_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO PUBLISHERS VALUES (
            PUBLISHERS_SEQ.NEXTVAL,
            V_PUBLISHER
        ) RETURNING ID INTO V_PUBLISHER_ID;
        RETURN V_PUBLISHER_ID;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_PUBLISHER;