CREATE OR REPLACE FUNCTION CHECK_READER (
    V_LIBRARY_CARD IN NUMBER
) RETURN NUMBER IS
    V_RESULT       NUMBER;
    V_DEBT NUMBER;
    V_ERROR_CODE   NUMBER;
    V_ERROR_MESAGE VARCHAR2(100);
BEGIN
    SELECT
        BLACK_LIST INTO V_RESULT
    FROM
        READERS
    WHERE
        LIBRARY_CARD = V_LIBRARY_CARD;

    SELECT
        COUNT(LIBRARY_CARD_ID) into V_DEBT
    FROM
        JOURNAL
    WHERE
        LIBRARY_CARD_ID = V_LIBRARY_CARD
        AND RETURN_DATE IS NULL
        AND (ROUND(SYSDATE) - ROUND(RECIVE_DATE)) > 30;

    IF (V_RESULT + V_DEBT) = 0 THEN
        RETURN 1;
    ELSIF V_RESULT = 1 THEN
        RETURN 0;
    ELSIF V_DEBT > 0 THEN
        RETURN 3;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 2;
    WHEN OTHERS THEN
        V_ERROR_CODE := SQLCODE;
        V_ERROR_MESAGE := SQLERRM;
END CHECK_READER;