CREATE SEQUENCE CHANGELOG_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE READERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE JOURNAL_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE BOOKS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE AUTHOR_STOCK_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE EMPLOYEES_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE POSITIONS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE AUTHORS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAG_STOCK_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE GENRE_STOCK_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE STOCK_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE AGE_LIMITS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TYPES_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE PUBLISHERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE TAGS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE GENRES_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;