--BOOKS
ALTER TABLE BOOKS
ADD CONSTRAINT BOOKS_Stock_ID_FK FOREIGN KEY (Stock_ID)
REFERENCES Stock(ID);

--EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_FK FOREIGN KEY (Position_id)
REFERENCES Employees(ID);


--JOURNAL 
ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_Employees_ID_FK FOREIGN KEY (Employees_ID)
REFERENCES Employees(ID);

ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_Book_ID_FK FOREIGN KEY (Book_ID)
REFERENCES Books(ID);

ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_Library_card_ID_FK FOREIGN KEY (Library_card_ID)
REFERENCES Readers(Library_card);


--STOCK
ALTER TABLE STOCK  
ADD CONSTRAINT STOCK_Publisher_ID_FK FOREIGN KEY (Publisher_ID)
REFERENCES Publishers(ID);

ALTER TABLE STOCK
ADD CONSTRAINT STOCK_Type_ID_FK FOREIGN KEY (Type_ID)
REFERENCES TYPES(ID);

ALTER TABLE STOCK
ADD CONSTRAINT STOCK_Age_limit_ID_FK FOREIGN KEY (Age_limit_ID)
REFERENCES Age_limits(ID);


--TAG_STOCK
ALTER TABLE TAG_STOCK
ADD CONSTRAINT TAG_STOCK_Tag_ID_FK FOREIGN KEY (Tag_ID)
REFERENCES Tags(ID);

ALTER TABLE TAG_STOCK
ADD CONSTRAINT TAG_STOCK_Stock_ID_FK FOREIGN KEY (Stock_ID)
REFERENCES Stock(ID);


--GENRE_STOCK
ALTER TABLE GENRE_STOCK
ADD CONSTRAINT GENRE_STOCK_Stock_ID_FK FOREIGN KEY (Stock_ID)
REFERENCES Stock(ID);

ALTER TABLE GENRE_STOCK
ADD CONSTRAINT GENRE_STOCK_Genre_ID_FK FOREIGN KEY (Genre_ID)
REFERENCES Genres(ID);


--AUTHOR_STOCK
ALTER TABLE AUTHOR_STOCK
ADD CONSTRAINT AUTHOR_STOCK_Author_ID_FK FOREIGN KEY (Author_ID)
REFERENCES Authors(ID);

ALTER TABLE AUTHOR_STOCK
ADD CONSTRAINT AUTHOR_STOCK_Stock_ID_FK FOREIGN KEY (Stock_ID)
REFERENCES Stock(ID);


--CHANGELOG
ALTER TABLE CHANGELOG
ADD CONSTRAINT CHANGELOG_Library_card_ID_FK FOREIGN KEY (Library_card_ID)
REFERENCES Readers(Library_card);

ALTER TABLE CHANGELOG
ADD CONSTRAINT CHANGELOG_Employee_ID_FK FOREIGN KEY (Employee_ID)
REFERENCES Employees(ID);