--BOOKS
ALTER TABLE BOOKS MODIFY STOCK_ID NOT NULL;
ALTER TABLE BOOKS MODIFY CONDITION NOT NULL;

--POSITIONS
ALTER TABLE POSITIONS MODIFY JOB_TITLE NOT NULL;

--EMPLOYEES
ALTER TABLE EMPLOYEES MODIFY NAME NOT NULL;
ALTER TABLE EMPLOYEES MODIFY SURNAME NOT NULL;
ALTER TABLE EMPLOYEES MODIFY POSITION_ID NOT NULL;

--READERS
ALTER TABLE READERS MODIFY NAME NOT NULL;
ALTER TABLE READERS MODIFY SURNAME NOT NULL;
ALTER TABLE READERS MODIFY RATING NOT NULL;
ALTER TABLE READERS MODIFY BIRTHD_DATE NOT NULL;
ALTER TABLE READERS MODIFY SEX NOT NULL;
ALTER TABLE READERS MODIFY BLACK_LIST NOT NULL;
ALTER TABLE READERS MODIFY MONEY NOT NULL;

--JOURNAL 
ALTER TABLE JOURNAL MODIFY RECIVE_DATE NOT NULL;
ALTER TABLE JOURNAL MODIFY LIBRARY_CARD_ID NOT NULL;
ALTER TABLE JOURNAL MODIFY BOOK_ID NOT NULL;
ALTER TABLE JOURNAL MODIFY EMPLOYEES_ID NOT NULL;

--STOCK
ALTER TABLE STOCK MODIFY BOOK_NAME NOT NULL;
ALTER TABLE STOCK MODIFY AMOUNT NOT NULL;
ALTER TABLE STOCK MODIFY PUBLICATION_YEAR NOT NULL;
ALTER TABLE STOCK MODIFY COST NOT NULL;
ALTER TABLE STOCK MODIFY TYPE_ID NOT NULL;
ALTER TABLE STOCK MODIFY AGE_LIMIT_ID NOT NULL;

--AGE_LIMITS
ALTER TABLE AGE_LIMITS MODIFY AGE NOT NULL;

--TYPES
ALTER TABLE TYPES MODIFY PUBLICATION_TYPE NOT NULL;

--TAG_STOCK
ALTER TABLE TAG_STOCK MODIFY TAG_ID NOT NULL;
ALTER TABLE TAG_STOCK MODIFY STOCK_ID NOT NULL;

--GENRE_STOCK
ALTER TABLE GENRE_STOCK MODIFY GENRE_ID NOT NULL;
ALTER TABLE GENRE_STOCK MODIFY STOCK_ID NOT NULL;

--AUTHOR_STOCK
ALTER TABLE AUTHOR_STOCK MODIFY AUTHOR_ID NOT NULL;
ALTER TABLE AUTHOR_STOCK MODIFY STOCK_ID NOT NULL;

--PUBLISHERS
ALTER TABLE PUBLISHERS MODIFY PUBLISHER_NAME NOT NULL;

--TAGS
ALTER TABLE TAGS MODIFY TAG_NAME NOT NULL;

--GENRES
ALTER TABLE GENRES MODIFY GENER_NAME NOT NULL;

--AUTHORS
ALTER TABLE AUTHORS MODIFY NAME NOT NULL;
ALTER TABLE AUTHORS MODIFY SURNAME NOT NULL;

--CHANGELOG
ALTER TABLE CHANGELOG MODIFY RECORDING_DATE NOT NULL;
ALTER TABLE CHANGELOG MODIFY LIBRARY_CARD_ID NOT NULL;
ALTER TABLE CHANGELOG MODIFY CHANGE NOT NULL;
ALTER TABLE CHANGELOG MODIFY EMPLOYEE_ID NOT NULL;