--BOOKS
ALTER TABLE BOOKS
ADD CONSTRAINT BOOKS_PK PRIMARY KEY (ID);

--POSITIONS
ALTER TABLE POSITIONS
ADD CONSTRAINT POSITIONS_PK PRIMARY KEY (ID);

--EMPLOYEES
ALTER TABLE EMPLOYEES
ADD CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID);

--READERS
ALTER TABLE READERS
ADD CONSTRAINT READERS_PK PRIMARY KEY (LIBRARY_CARD);

--JOURNAL 
ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_PK PRIMARY KEY (ID);

--AGE_LIMITS
ALTER TABLE AGE_LIMITS
ADD CONSTRAINT AGE_LIMITS_PK PRIMARY KEY (ID);

--TYPES
ALTER TABLE TYPES
ADD CONSTRAINT TYPES_PK PRIMARY KEY (ID);

--PUBLISHERS
ALTER TABLE PUBLISHERS
ADD CONSTRAINT PUBLISHERS_PK PRIMARY KEY (ID);

--STOCK
ALTER TABLE STOCK
ADD CONSTRAINT STOCK_PK PRIMARY KEY (ID);

--TAGS
ALTER TABLE TAGS
ADD CONSTRAINT TAGS_PK PRIMARY KEY (ID);

--GENRES
ALTER TABLE GENRES
ADD CONSTRAINT GENRES_PK PRIMARY KEY (ID);

--AUTHORS
ALTER TABLE AUTHORS
ADD CONSTRAINT AUTHORS_PK PRIMARY KEY (ID);

--CHANGELOG
ALTER TABLE CHANGELOG
ADD CONSTRAINT CHANGELOG_PK PRIMARY KEY (ID);

--TAG_STOCK
ALTER TABLE TAG_STOCK
ADD CONSTRAINT TAG_STOCK_PK PRIMARY KEY (ID);


--GENRE_STOCK
ALTER TABLE GENRE_STOCK
ADD CONSTRAINT GENRE_STOCK_PK PRIMARY KEY (ID);

--AUTHOR_STOCK
ALTER TABLE AUTHOR_STOCK
ADD CONSTRAINT AUTHOR_STOCK_PK PRIMARY KEY (ID);