CREATE OR REPLACE FUNCTION FINDE_READER (
    V_NAME IN VARCHAR2,
    V_SURNAME IN VARCHAR2,
    V_BIRTHD_DATE IN DATE
) RETURN NUMBER IS
    V_RESULT NUMBER;
BEGIN
    SELECT
        LIBRARY_CARD INTO V_RESULT
    FROM
        READERS
    WHERE
        BIRTHD_DATE = V_BIRTHD_DATE
        AND NAME = V_NAME
        AND SURNAME = V_SURNAME;
    RETURN V_RESULT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END FINDE_READER;