CREATE OR REPLACE FUNCTION INSERT_IN_READERS (
    V_NAME IN VARCHAR2,
    V_SURNAME IN VARCHAR2,
    V_BIRTHD_DATE IN DATE
) RETURN NUMBER IS
    V_RATING     NUMBER := 400;
    V_BLACK_LIST NUMBER := 0;
    V_READER_ID  NUMBER;
BEGIN
    INSERT INTO READERS VALUES (
        READERS_SEQ.NEXTVAL,
        V_NAME,
        V_SURNAME,
        V_BIRTHD_DATE,
        V_RATING,
        V_BLACK_LIST,
        SYSDATE
    ) RETURNING LIBRARY_CARD INTO V_READER_ID;
    COMMIT;
    RETURN V_READER_ID;
END INSERT_IN_READERS;