CREATE TABLE POSITIONS(
    ID NUMBER GENERATED AS IDENTITY,
    JOB_TITLE VARCHAR2(100),
    CONSTRAINT POSITIONS_PK PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEES(
    ID NUMBER GENERATED AS IDENTITY,
    NAME VARCHAR2(100),
    SURNAME VARCHAR2(100),
    POSITION_ID NUMBER,
    CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID)
);

CREATE TABLE READERS(
    LIBRARY_CARD NUMBER GENERATED AS IDENTITY,
    NAME VARCHAR2(100),
    SURNAME VARCHAR2(100),
    BIRTHD_DATE DATE,
    RATING NUMBER,
    SEX VARCHAR2(100),
    BLACK_LIST NUMBER,
    MONEY NUMBER,
    CONSTRAINT READERS_PK PRIMARY KEY (LIBRARY_CARD)
);

CREATE TABLE JOURNAL(
    ID NUMBER GENERATED AS IDENTITY,
    RECIVE_DATE DATE,
    RETURN_DATE DATE,
    LIBRARY_CARD_ID NUMBER,
    BOOK_ID NUMBER,
    BOOK_RATING NUMBER,
    WHERE_READS VARCHAR2(100),
    EMPLOYEES_ID NUMBER,
    CONSTRAINT JOURNAL_PK PRIMARY KEY (ID)
);

CREATE TABLE STOCK(
    ID NUMBER GENERATED AS IDENTITY,
    BOOK_NAME VARCHAR2(400),
    AMOUNT NUMBER,
    PUBLICATION_YEAR NUMBER,
    COST NUMBER(8, 2),
    PUBLISHER_ID NUMBER,
    TYPE_ID NUMBER,
    AGE_LIMIT_ID NUMBER,
    DESCRIPTION VARCHAR2(4000),
    PURCHASE_TYPE VARCHAR2(400),
    CONSTRAINT STOCK_PK PRIMARY KEY (ID)
);

CREATE TABLE BOOKS(
    ID NUMBER GENERATED AS IDENTITY,
    STOCK_ID NUMBER,
    CONDITION NUMBER,
    CONSTRAINT BOOKS_PK PRIMARY KEY (ID)
);

CREATE TABLE AGE_LIMITS(
    ID NUMBER GENERATED AS IDENTITY,
    AGE NUMBER,
    CONSTRAINT AGE_LIMITS_PK PRIMARY KEY (ID)
);

CREATE TABLE TYPES(
    ID NUMBER GENERATED AS IDENTITY,
    PUBLICATION_TYPE VARCHAR2(100),
    CONSTRAINT PUBLICATION_TYPES PRIMARY KEY (ID)
);

CREATE TABLE TAG_STOCK(
    ID NUMBER GENERATED AS IDENTITY,
    TAG_ID NUMBER,
    STOCK_ID NUMBER,
    CONSTRAINT TAG_BOOK PRIMARY KEY (ID)
);

CREATE TABLE GENRE_STOCK(
    ID NUMBER GENERATED AS IDENTITY,
    GENRE_ID NUMBER,
    STOCK_ID NUMBER,
    CONSTRAINT GENRE_BOOK PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR_STOCK(
    ID NUMBER GENERATED AS IDENTITY,
    AUTHOR_ID NUMBER,
    STOCK_ID NUMBER,
    CONSTRAINT AUTHOR_STOCK_PK PRIMARY KEY (ID)
);

CREATE TABLE PUBLISHERS(
    ID NUMBER GENERATED AS IDENTITY,
    PUBLISHER_NAME VARCHAR2(100),
    CONSTRAINT PUBLISHERS PRIMARY KEY (ID)
);

CREATE TABLE TAGS(
    ID NUMBER GENERATED AS IDENTITY,
    TAG_NAME VARCHAR2(100),
    CONSTRAINT TAGS PRIMARY KEY (ID)
);

CREATE TABLE GENRES(
    ID NUMBER GENERATED AS IDENTITY,
    GENER_NAME VARCHAR2(100),
    CONSTRAINT GENRES_PK PRIMARY KEY (ID)
);

CREATE TABLE AUTHORS(
    ID NUMBER GENERATED AS IDENTITY,
    NAME VARCHAR2(100),
    SURNAME VARCHAR2(100),
    CONSTRAINT AUTHORS_PK PRIMARY KEY (ID)
);

CREATE TABLE CHANGELOG(
    ID NUMBER GENERATED AS IDENTITY,
    RECORDING_DATE DATE,
    LIBRARY_CARD NUMBER,
    CHANGE VARCHAR2(100),
    EMPLOYEE_ID NUMBER,
    CONSTRAINT CHANGELOG_PK PRIMARY KEY (ID)
);